stages:
  - build
  - release

variables:
  OUTPUT_DIR: dist
  APP_ID: "app.fluxloader.FluxLoader"
  PRODUCT_NAME: "FluxLoader"
  LEGACY_ELECTRON_VERSION: "22.3.27"

.build_template:
  stage: build
  tags:
    - linux
  image: node:20
  before_script:
    - dpkg --add-architecture i386
    # Corrected apt-get install line using >- to fold lines w/ spaces, removing bad '\'
    - >-
      apt-get update && apt-get install -y --no-install-recommends
      wine
      build-essential gcc g++ make git python3
      dpkg fakeroot
      libarchive-tools
      icnsutils graphicsmagick xz-utils
      clang libc++-dev libc++abi-dev libgconf-2-4 rpm libx11-dev libxkbfile-dev
      libsecret-1-dev libgbm-dev
      && rm -rf /var/lib/apt/lists/*
    - echo "--- Wine Debug Info ---"
    - which wine || echo "wine not found in PATH"
    - which wine64 || echo "wine64 not found in PATH"
    - which wine32 || echo "wine32 not found in PATH"
    - dpkg -l | grep wine || echo "No wine packages found via dpkg"
    - wine --version || echo "wine --version command failed"
    - echo "--- Environment PATH ---"
    - printenv PATH
    - echo "--- End Debug Info ---"
    - npm install -g npm@latest
    - echo "Cleaning npm cache..."
    - npm cache clean --force
    - echo "Installing project dependencies..."
    - npm install --legacy-peer-deps --no-audit --prefer-offline --progress=false
    - echo "Node modules installed."
    - ls node_modules || echo "node_modules not found after install!"
    - echo "Removing existing electron-builder directory if present..."
    - rm -rf node_modules/electron-builder
    - echo "Installing LATEST electron-builder explicitly for the job..."
    - npm install electron-builder@latest --no-save --legacy-peer-deps --no-audit
    - echo "electron-builder installed."
    - echo "Verifying electron-builder version:"
    - ./node_modules/.bin/electron-builder --version || echo "Cannot get electron-builder version via direct path"
  script:
    - set -eo pipefail
    - echo "Starting build for $CI_JOB_NAME"
    - rm -rf $OUTPUT_DIR && mkdir -p $OUTPUT_DIR
  artifacts:
    paths:
      - $OUTPUT_DIR/
    expire_in: 1 week

build-windows-x64:
  extends: .build_template
  script:
    - !reference [.build_template, script]
    - ./node_modules/.bin/electron-builder --win --x64 --config.appId="$APP_ID" --config.productName="$PRODUCT_NAME" --config.directories.output="$OUTPUT_DIR" --config.buildVersion="$CI_COMMIT_TAG" --config.win.target=nsis --config.asar=true --publish never

build-windows-arm64:
  extends: .build_template
  script:
    - !reference [.build_template, script]
    - ./node_modules/.bin/electron-builder --win --arm64 --config.appId="$APP_ID" --config.productName="$PRODUCT_NAME" --config.directories.output="$OUTPUT_DIR" --config.buildVersion="$CI_COMMIT_TAG" --config.win.target=nsis --config.asar=true --publish never

build-windows-legacy-x64:
  extends: .build_template
  before_script:
    - !reference [.build_template, before_script]
    - echo "Installing legacy Electron version $LEGACY_ELECTRON_VERSION..."
    - npm install --save-dev electron@$LEGACY_ELECTRON_VERSION --legacy-peer-deps --no-audit
    - echo "Legacy Electron installed."
  script:
    - !reference [.build_template, script]
    - ./node_modules/.bin/electron-builder --win --x64 --config.appId="$APP_ID.legacy" --config.productName="$PRODUCT_NAME-Legacy" --config.directories.output="$OUTPUT_DIR" --config.buildVersion="$CI_COMMIT_TAG" --config.win.target=nsis --config.asar=true --publish never

build-linux-x64:
  extends: .build_template
  script:
    - !reference [.build_template, script]
    - ./node_modules/.bin/electron-builder --linux --x64 --config.appId="$APP_ID" --config.productName="$PRODUCT_NAME" --config.directories.output="$OUTPUT_DIR" --config.buildVersion="$CI_COMMIT_TAG" --config.linux.target=AppImage,deb --config.asar=true --publish never

build-linux-arm64:
  extends: .build_template
  script:
    - !reference [.build_template, script]
    - ./node_modules/.bin/electron-builder --linux --arm64 --config.appId="$APP_ID" --config.productName="$PRODUCT_NAME" --config.directories.output="$OUTPUT_DIR" --config.buildVersion="$CI_COMMIT_TAG" --config.linux.target=AppImage,deb --config.asar=true --publish never

build-macos-x64:
  extends: .build_template
  script:
    - !reference [.build_template, script]
    - ./node_modules/.bin/electron-builder --mac --x64 --config.appId="$APP_ID" --config.productName="$PRODUCT_NAME" --config.directories.output="$OUTPUT_DIR" --config.buildVersion="$CI_COMMIT_TAG" --config.mac.target=dmg --config.mac.identity=null --config.asar=true --publish never

build-macos-arm64:
  extends: .build_template
  script:
    - !reference [.build_template, script]
    - ./node_modules/.bin/electron-builder --mac --arm64 --config.appId="$APP_ID" --config.productName="$PRODUCT_NAME" --config.directories.output="$OUTPUT_DIR" --config.buildVersion="$CI_COMMIT_TAG" --config.mac.target=dmg --config.mac.identity=null --config.asar=true --publish never

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - linux
  needs:
    - job: build-windows-x64
      artifacts: true
    - job: build-windows-arm64
      artifacts: true
    - job: build-windows-legacy-x64
      artifacts: true
    - job: build-linux-x64
      artifacts: true
    - job: build-linux-arm64
      artifacts: true
    - job: build-macos-x64
      artifacts: true
    - job: build-macos-arm64
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Starting release process for tag $CI_COMMIT_TAG"
    - echo "Files in $OUTPUT_DIR:"
    - ls -l $OUTPUT_DIR/
    - |
      ASSETS_JSON="["
      FIRST_ASSET=true
      find $OUTPUT_DIR -maxdepth 1 -type f -print0 | while IFS= read -r -d $'\0' file; do
          filename=$(basename "$file")
          filepath="/$filename"
          display_name=$(echo "$filename" | sed 's/"/\\"/g')

          PACKAGE_UPLOAD_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PRODUCT_NAME}/${CI_COMMIT_TAG}"
          PACKAGE_DOWNLOAD_URL="${PACKAGE_UPLOAD_URL}/${filename}"

          echo "Uploading ${filename} to Generic Package Registry..."
          curl --fail --retry 5 --retry-delay 2 --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
               --upload-file "$file" \
               "${PACKAGE_UPLOAD_URL}/${filename}" || exit 1
          echo "Upload complete for ${filename}."

          if [ "$FIRST_ASSET" = true ]; then
              FIRST_ASSET=false
          else
              ASSETS_JSON="${ASSETS_JSON},"
          fi

          ASSETS_JSON="${ASSETS_JSON}{\"name\":\"${display_name}\",\"url\":\"${PACKAGE_DOWNLOAD_URL}\",\"filepath\":\"${filepath}\",\"link_type\":\"package\"}"
      done
      ASSETS_JSON="${ASSETS_JSON}]"

      echo "Generated Assets JSON: ${ASSETS_JSON}"
    - echo "Creating GitLab Release..."
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" \
                         --tag-name "$CI_COMMIT_TAG" \
                         --description "Automated release for tag $CI_COMMIT_TAG. Download builds from the assets below." \
                         --assets-link "${ASSETS_JSON}"
    - echo "GitLab Release created successfully!"