name: Build & Release

on:
    push:
        tags:
            - "*"

env:
    OUTPUT_DIR: dist

permissions:
  contents: write

jobs:
    build-windows-x64:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm install --legacy-peer-deps --no-audit
            - run: npx electron-builder --win portable --x64
            - uses: actions/upload-artifact@v4
              with:
                  name: windows-x64
                  path: dist/*.exe     

    release:
        needs:
            - build-windows-x64
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: windows-x64
                  path: dist
            
            - name: Create Release
              uses: actions/create-release@v1
              id: create_release
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload assets
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: dist/Fluxloader-${{ github.ref_name }}-win-x64.exe
                  asset_name: Fluxloader-${{ github.ref_name }}-win-x64.exe
                  asset_content_type: application/octet-stream
